kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: node:18-slim
    volumes:
      - name: yarn-cache
        path: /cache/yarn
    environment:
      YARN_CACHE_FOLDER: /cache/yarn
    commands:
      - yarn install
      - yarn build

  - name: publish
    image: node:18-slim
    commands:
      - echo "//registry.npmjs.org/:_authToken=\$TOKEN" > ~/.npmrc
      - npm whoami
    environment:
      TOKEN:
        from_secret: npm_token
    access: public
    when:
      branch:
        - release

volumes:
  - name: yarn-cache
    host:
      path: /var/cache/drone/yarn
